name: Deploy Portfolio Website to gitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    #checkout the code
      - name: Checkout code
        uses: actions/checkout@v6
    #set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '18'
    #install dependencies
      - name: Install dependencies
        run: npm install
    #build the project
      - name: Build project
        run: npm run build
    #deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist